import {Platform} from 'react-native';
import LocalizedStrings from 'react-native-localization';

const Strings = new LocalizedStrings({
  en: {
    common: {
      welcome: `Welcome to\nLet’s Walk!`,
      next: 'Next',
      submit: 'Submit',
      today: 'Today',
      yesterday: 'Yesterday',
      noWalks: 'No Recorded Walks',
      home: 'Home',
      back: 'Back',
      myRecordedWalks: 'My Recorded Walks',
      about: `Let’s Walk Information`,
      programPartners: 'Program Partners',
      topWalkers: 'Top Walkers',
      whereToWalk: 'Where to Walk',
      emailUs: 'Email Us',
      contestRules: 'Contest Rules',
      privacyPolicy: 'Privacy Policy',
      signOut: 'Sign out',
      deleteUser: 'Delete Account',
      steps: 'steps',
      miles: 'miles',
      mins: 'mins',
      morningWalk: 'Morning Walk',
      afternoonWalk: 'Afternoon Walk',
      eveningWalk: 'Evening Walk',
      okay: 'Okay',
      pleaseWait: 'Please wait...',
      serverErrorTitle: 'Unexpected error',
      serverErrorMessage:
        `We could not communicate with the Let’s Walk Server. Please check your Internet connection and try again.`,
      date: 'MMMM D',
      range: '{0} - {1}',
      rangeFrom: 'MMMM D',
      rangeTo: 'MMMM D, YYYY',
      dateSlash: 'MM/DD/YYYY',
      save: 'Save',
    },
    notifications: {
      repeatingRecordingReminder:
        "You've been walking for over an hour. Don't forget to stop recording your walk if you're done!",
    },
    partners: {
      thanks: `Special thanks to all the Let’s Walk partners!`,
      text: `Let’s Walk is run by the SF Department of Public Health. It is funded by USDA SNAP, an equal opportunity provider. Community partners include the California Department of Public Health, SF Civic Tech, San Francisco Giants, and the SF Recreation and Parks Department.`,
    },
    recorder: {
      finish: 'Save',
      resume: 'Resume',
      stopAndSave: 'Stop & Save',
      stop: 'Stop',
      pause: 'Pause',
      paused: 'Paused',
      recording: 'Recording',
      save: 'Save {0}',
    },
    welcome: {
      select: 'Please select a language',
      start: 'Start',
    },
    signUp: {
      about:
        `Let’s Walk is a FREE community walking program that runs from {0}. The program is open to CalFresh/MediCal-eligible San Francisco residents. Top walkers will be eligible for prizes from the San Francisco Giants! Sign up below to get started!`,
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      zipCode: 'Zip Code',
      age: 'Age',
      required: '* All fields required',
      agree: 'By signing up, I agree to the {0} and {1}.',
      policy: 'Privacy Policy',
      contestRules: 'Contest Rules',
      ageAlertTitle: 'Age Restriction',
      ageMinMessage:
        `You must be at least 18 years old to participate in Let’s Walk.`,
      ageMaxMessage: 'Please enter a valid age.',
      emailAlertTitle: 'Email Required',
      emailAlertMessage: 'Please enter a valid email address.',
      zipRestrictionAlertTitle: 'Zip Code Restriction',
      zipRestrictionAlertMessage:
        `You must be a San Francisco resident to participate in Let’s Walk.`,
    },
    info: {
      youreSignedUp: 'You’re Signed Up!',
      fromHereText: 'From here, participating is easy.',
      walk: 'Walk!',
      walkText:
        'This app will count your total steps taken each day, just carry your phone with you when you’re walking.',
      record: 'Record!',
      recordText:
        'Use this feature to track your walks. Challenge yourself to increase distance and time!',
      win: 'Win!',
      winText:
        'At the end of the program, the top 10 walkers will be contacted by email to claim their prize. Prizes provided by the SF Giants!',
    },
    permissions: {
      thingsToKnow: 'Things to know.',
      takeALookText: 'Take a look at this information before you get started.',
      settingsText: `The Let’s Walk App uses ${Platform.select({
        ios: 'Apple Health',
        android: 'Google Fit',
      })} to keep track of your steps. In the next screens, you will be asked to allow Let’s Walk to use this information.`,
      prizeText: `To win a prize through Let’s Walk, you must allow the Let’s Walk App to use ${Platform.select(
        {ios: 'Apple Health', android: 'Google Fit'},
      )} information. All information will be kept private and used only for the Let’s Walk Program.`,
      googleText:
        'Google Fit requires a Google account, if you do not have one, {0}.',
      getOneHere: 'learn how to get one here',
    },
    home: {
      stepsToday: 'steps today',
      milesSuffix: '',
      milesToday: 'miles today',
      overallStepTotal: 'overall step total',
      stepsThisMonth: 'total steps this month',
      topWalkers: 'Top Walkers',
      whereToWalk: 'Where to Walk?',
      myRecordedWalks: 'My Recorded Walks Today',
      allRecordedWalks: 'All Recorded Walks',
      noWalksYet: 'No Walks Yet',
      noWalksYetText:
        'Start a new walk by pressing the record button at the bottom of the screen.',
      recordAWalk: 'Record a New Walk',
      getReadyAlert1: 'Get ready to start the challenge!',
      getReadyAlert2:
        'On {0} your step total will reset and your steps will start being counted towards winning prizes.',
      currentAlert: 'Current Walking Challenge: {0} - {1}',
      congratsAlert:
        'Congratulations on all of that great walking! You will receive an email if you are a top walker and have won a prize! The challenge is now over but you can keep using the app to track your steps.',
      noContestAlert: 'No current walking challenge, but keep up the walking!',
      myGoals: 'My Goals',
    },
    whereToWalk: {
      options:
        'The San Francisco Rec & Parks Department has many activity options!',
      parksAndRecCenters: 'Parks & Rec Centers',
      hikingTrailsInSF: 'Hiking Trails in SF',
      guidedWalks: 'Explore Nature',
      exerciseAndFitnessActivities: 'Exercise & Fitness Activities',
    },
    about: {
      what: `What is Let’s Walk?`,
      whatText:
        `Let’s Walk is a FREE community walking program that runs from {0}. The program is open to CalFresh/MediCal-eligible San Francisco residents. Prizes will be awarded to the top walkers at the end of the program.`,
      dates: 'What are the key dates?',
      datesText:
        'On {0}, your steps will start at zero and the walking challenge will begin! All of your steps from {1} will count towards winning a prize. After the program is over, you can use the app, but no additional prizes will be awarded.',
      prize: 'How do I win a prize?',
      prizeText:
        'At the end of the program, the top 10 walkers will be contacted by email to claim their prize. Prizes provided by the SF Giants!',
    },
    latinOrHispanicOrigin: {
      select: 'Please select from the choices below',
      question: 'Are you of Latino or Hispanic origin?',
      questionSub: '',
      yes: 'Yes',
      no: 'No',
      declineToAnswer: 'Decline to answer',
      disclaimer: 'Information collected will be used for program improvements',
    },
    whatIsYourRace: {
      question: 'What is your race?',
      questionSub: 'If multiracial, check all that apply',
      americanNative: 'American Indian or\nAlaska Native',
      asian: 'Asian',
      black: 'Black or African American',
      pacificIsl: 'Native Hawaiian or\nOther Pacific Islander',
      white: 'White',
      other: 'Other',
      otherSub: 'Please fill in:',
      cannotBeEmpty: 'This field cannot be empty',
      declineToAnswer: 'Decline to answer',
    },
    whatIsYourGenderIdentity: {
      question: 'What is your gender identity?',
      questionSub: '',
      female: 'Female',
      male: 'Male',
      transFemale: 'Trans Female',
      transMale: 'Trans Male',
      nonBinary: 'Non-binary',
      other: 'Other',
      otherSub: 'Please fill in:',
      cannotBeEmpty: 'This field cannot be empty',
      declineToAnswer: 'Decline to answer',
    },
    whatIsYourSexualOrientation: {
      question: 'How do you describe your sexual orientation or sexual identy?',
      questionSub: '',
      bisexual: 'Bisexual',
      sameGenderLoving: 'Gay/Lesbian/Same-Gender Loving',
      unsure: 'Questioning/Unsure',
      heterosexual: 'Straight/Heterosexual',
      other: 'Other',
      otherSub: 'Please fill in:',
      cannotBeEmpty: 'This field cannot be empty',
      declineToAnswer: 'Decline to answer',
    },
    deleteUser: {
      popupText: 'Are you sure you want to delete ALL of your saved data?',
      yesDelete: 'Yes, delete',
      noGoBack: 'No, go back',
    },
    logout: {
      popupText: 'Are you sure you want to sign out?',
      yesDelete: 'Yes',
      noGoBack: 'No, go back',
    },
    leaderBoard: {
      thisIsYou: 'This is You!',
      walkerGeneral: 'Walker',
      available: 'Only available during the summer: {0}',
      keepWalking: 'Keep walking!',
    },
    setYourStepGoal: {
      header: 'Set your step goal',
      instructions: 'Tap the buttons to change your step goal',
      stepText: 'I want to walk…',
      daysText: 'How often?',
      decreaseSteps: '-500 steps',
      increaseSteps: '+500 steps',
      decreaseDays: '-1 day',
      increaseDays: '+1 day',
      stepsPerDay: 'steps/day',
      dayPerWeek: 'day/week',
      daysPerWeek: 'days/week',
    },
    stepGoalProgress: {
      thisWeek: 'This Week',
      pastWeek: 'Past Week',
      myGoal: 'My Goal',
      day: 'day',
      days: 'days',
      for: 'for',
      inProgress: 'Goal In Progress',
      goalMet: 'Goal Met',
      goalNotMet: 'Goal Not Met',
      changeMyGoal: 'Change my goal',
      today: 'Today',
      stepsToday: 'steps today',
      avgStepsPerDay: 'average steps/day',
      moreStepsToGo: 'more steps to go',
      totalStepsThisWeek: 'total steps this week',
      mon: 'Mo',
      tue: 'Tu',
      wed: 'We',
      thu: 'Th',
      fri: 'Fr',
      sat: 'Sa',
      sun: 'Su',
    },
  },
  es: {
    common: {
      welcome: 'Bienvenido a\nVamos a Caminar!',
      next: 'Siguiente',
      submit: 'Enviar',
      today: 'Hoy',
      yesterday: 'Ayer',
      noWalks: 'No hay caminatas grabadas',
      home: 'Inicio',
      back: 'Atrás',
      myRecordedWalks: 'Mis Caminatas Grabadas',
      about: `Información de Let’s Walk`,
      programPartners: 'Socios del Programa',
      topWalkers: 'Mejores Caminantes',
      whereToWalk: 'Por Dónde Caminar',
      emailUs: 'Contáctanos',
      contestRules: 'Reglas Oficiales',
      privacyPolicy: 'Política de Privacidad',
      signOut: 'Cerrar sesión',
      deleteUser: 'Eliminar cuenta',
      steps: 'pasos',
      miles: 'millas',
      mins: 'minutos',
      morningWalk: 'Caminata Matutina',
      afternoonWalk: 'Caminata por la Tarde',
      eveningWalk: 'Caminata Nocturna',
      okay: 'Está Bien',
      pleaseWait: 'Por favor espera...',
      serverErrorTitle: 'Error inesperado',
      serverErrorMessage:
        `No pudimos comunicarnos con el servidor de Let’s Walk. Por favor verifica tu conexión de internet e intenta nuevamente.`,
      date: 'D [de] MMMM',
      range: '{0} al {1}',
      rangeFrom: 'D [de] MMMM',
      rangeTo: 'D [de] MMMM [del] YYYY',
      dateSlash: 'MM/DD/YYYY',
      save: 'Guardar',
    },
    notifications: {
      repeatingRecordingReminder:
        'Has estado caminando por más de una hora. ¡No olvides dejar de grabar tu caminata si ya terminaste!',
    },
    partners: {
      thanks: `¡Un agradecimiento especial a todos los socios de Vamos a Caminar (Let’s Walk)!`,
      text: 'Vamos a Caminar (Let’s Walk) es dirigido por el Departamento de Salud Pública de SF. Es financiado por SNAP del USDA, un proveedor que brinda igualdad de oportunidades.  Los socios comunitarios incluyen el Departamento de Salud Pública de California, SF Civic Tech, los Gigantes de San Francisco y el Departamento de Recreación y Parques de SF.',
    },
    recorder: {
      finish: 'Guardar',
      resume: 'Reniciar',
      stopAndSave: 'Parar y guardar',
      stop: 'Parar',
      pause: 'Pausa',
      paused: 'Pausada',
      recording: 'Grabación',
      save: 'Guardando {0}',
    },
    welcome: {
      select: 'Por favor selecciona un idioma.',
      start: 'Iniciar',
    },
    signUp: {
      about:
        'Vamos a Caminar (Let’s Walk) es un programa GRATUITO de caminata comunitaria que se llevará a cabo del {0}. El programa está abierto para residentes de San Francisco elegibles para CalFresh / MediCal. ¡Los mejores caminantes serán elegibles para recibir premios de los Gigantes de San Francisco. ¡Inscríbete para comenzar!',
      firstName: 'Primer Nombre',
      lastName: 'Apellido',
      email: 'Correo electrónico',
      zipCode: 'Código postal',
      age: 'Edad',
      required: '* Todos los campos son requeridos',
      agree: 'Al registrarme, acepto la {0} y {1}.',
      policy: 'Política de Privacidad',
      contestRules: 'las Reglas oficiales del programa',
      ageAlertTitle: 'Restricción de edad',
      ageMinMessage: `Debes tener al menos 18 años para participar en Vamos a Caminar (Let’s Walk).`,
      ageMaxMessage: 'Ingresa una edad válida.',
      emailAlertTitle: 'Correo Electrónico',
      emailAlertMessage:
        'Por favor, introduce una dirección de correo electrónico válida.',
      zipRestrictionAlertTitle: 'Restricción de código postal',
      zipRestrictionAlertMessage:
        `Debes ser residente de San Francisco para participar en Vamos a Caminar (Let’s Walk).`,
    },
    info: {
      youreSignedUp: '¡Estas registrado!',
      fromHereText: 'Desde aquí, participar es fácil!',
      walk: '¡Caminar!',
      walkText:
        'Esta aplicación contará los pasos totales que tomas cada día, solo lleva tu teléfono contigo mientras caminas.',
      record: '¡Grabar!',
      recordText:
        'Usa esta función para grabar tus caminatas. ¡Desafíate a ti mismo para aumentar el tiempo y la distancia!',
      win: '¡Ganar!',
      winText:
        'Al final del programa, los 10 mejores caminantes serán contactados por correo electrónico para reclamar su premio. ¡Premios proporcionados por los Gigantes de SF!',
    },
    permissions: {
      thingsToKnow: 'Cosas que debes saber.',
      takeALookText: 'Echa un vistazo a esta información antes de comenzar.',
      settingsText: `La aplicación Let’s Walk utiliza datos recopilados por ${Platform.select(
        {ios: 'Apple Health', android: 'Google Fit'},
      )} para grabar con precisión tus pasos diarios. En las siguientes pantallas, se te pedirá que des permiso para que Let’s Walk acceda a esta información.`,
      prizeText:
        'Todos los participantes que deseen ser elegibles para premios a través de Vamos a Caminar (Let’s Walk) deben dar permiso para acceder a esta información. Todos los datos proporcionados se mantendrán privados y se utilizarán estrictamente para el propósito del Programa Vamos a Caminar (Let’s Walk).',
      googleText:
        'Google Fit requiere una cuenta de Google, si no tienes una, {0}.',
      getOneHere: 'aprende cómo obtenerla aquí',
    },
    home: {
      stepsToday: 'pasos hoy',
      milesSuffix: '',
      milesToday: 'millas hoy',
      overallStepTotal: 'recuento total de pasos',
      stepsThisMonth: 'pasos totales este mes',
      topWalkers: 'Mejores Caminantes',
      whereToWalk: '¿Necesitas un lugar para caminar?',
      myRecordedWalks: 'Mis caminatas grabadas hoy',
      allRecordedWalks: 'Todas las caminatas grabadas',
      noWalksYet: 'Todavía no hay caminatas',
      noWalksYetText:
        'Comienza una nueva caminata presionando el botón de grabación en la parte inferior de la pantalla.',
      recordAWalk: 'Grabar una nueva caminata',
      getReadyAlert1: '¡Prepárate para comenzar el desafío!',
      getReadyAlert2:
        'El {0} tu recuento total de pasos reiniciará y tus pasos comenzarán a ser contados para ganar premios.',
      currentAlert: 'Desafío de caminata actual: {0} - {1}',
      congratsAlert:
        '¡Felicitaciones por esa gran caminata! ¡Recibirás un correo electrónico si eres uno de los mejores caminantes y has ganado un premio! El desafío ya ha terminado, pero puedes seguir usando la aplicación para seguir tus pasos.',
      noContestAlert:
        'Actualmente no hay desafíos para caminar, ¡pero sigue caminando!',
      myGoals: 'Mis Metas',
    },
    whereToWalk: {
      options:
        '¡El Departamento de Recreación y Parques de San Francisco tiene muchas opciones de actividades!',
      parksAndRecCenters: 'Parques y Centros de Recreación',
      hikingTrailsInSF: 'Rutas de Senderismo en SF',
      guidedWalks: 'Explorar la Naturaleza',
      exerciseAndFitnessActivities: 'Ejercicio y Actividades Físicas',
    },
    about: {
      what: '¿Qué es Vamos a Caminar?',
      whatText:
        'Vamos a Caminar (Let’s Walk) es un programa GRATUITO de caminata comunitaria que se llevará a cabo del {0}. El programa está abierto para residentes de San Francisco elegibles para CalFresh / MediCal. Se otorgarán premios a los mejores caminantes al final del programa.',
      dates: '¿Cuáles son las fechas importantes?',
      datesText:
        'El {0}, tus pasos comenzarán en cero y el desafío de caminar comenzará! Todos tus pasos del {1} contarán para ganar un premio. Una vez finalizado el programa, puedes utilizar la aplicación, pero no se otorgarán premios adicionales.',
      prize: '¿Cómo gano un premio?',
      prizeText:
        'Al final del programa, los 10 mejores caminantes serán contactados por correo electrónico para reclamar su premio. ¡Premios proporcionados por los Gigantes de SF!',
    },
    latinOrHispanicOrigin: {
      select: 'Por favor seleccione entre las siguientes opciones',
      question: '¿Eres de origen latino o hispano?',
      questionSub: '',
      yes: 'Sí',
      no: 'No',
      declineToAnswer: 'Prefiero no contestar',
      disclaimer:
        'La información recopilada se utilizará para mejorar el programa',
    },
    whatIsYourRace: {
      question: '¿Cuál es tu raza?',
      questionSub:
        'Si eres multirracial, selecciona todas las que correspondan.',
      americanNative: 'Indio americano o nativo de Alaska',
      asian: 'Asiático',
      black: 'Negro o afroamericano',
      pacificIsl: 'Nativo de Hawai u otra isla del Pacífico',
      white: 'Blanco',
      other: 'Otro',
      otherSub: 'Por favor completa:',
      cannotBeEmpty: 'Este campo no puede estar vacío',
      declineToAnswer: 'Prefiero no contestar',
    },
    whatIsYourGenderIdentity: {
      question: '¿Cuál es tu identidad de género?',
      questionSub: '',
      female: 'Mujer',
      male: 'Hombre',
      transFemale: 'Mujer trans',
      transMale: 'Hombre trans',
      nonBinary: 'No binario',
      other: 'Otro',
      otherSub: 'Por favor completa:',
      cannotBeEmpty: 'Este campo no puede estar vacío',
      declineToAnswer: 'Prefiero no contestar',
    },
    whatIsYourSexualOrientation: {
      question: '¿Cómo describes tu orientación sexual o identidad sexual?',
      questionSub: '',
      bisexual: 'Bisexual',
      sameGenderLoving: 'Homosexual/Lesbiana/Amante del mismo género',
      unsure: 'Cuestionando/No estoy seguro(a)',
      heterosexual: 'Heterosexual',
      other: 'Otro',
      otherSub: 'Por favor completa:',
      cannotBeEmpty: 'Este campo no puede estar vacío',
      declineToAnswer: 'Prefiero no contestar',
    },
    deleteUser: {
      popupText:
        '¿Estás seguro de que deseas eliminar TODOS tus datos guardados?',
      yesDelete: 'Sí, eliminar',
      noGoBack: 'No, regresar',
    },
    logout: {
      popupText: '¿Estás seguro de que quieres cerrar sesión?',
      yesDelete: 'Sí',
      noGoBack: 'No, regresar',
    },
    leaderBoard: {
      thisIsYou: '¡eres tú!',
      walkerGeneral: 'Caminante',
      available: 'Sólo disponible durante el verano: {0}',
      keepWalking: '¡Sigue caminando!',
    },
    setYourStepGoal: {
      header: 'Establece tu objetivo de pasos',
      instructions: 'Toca los botones para cambiar tu objetivo de pasos',
      stepText: 'Quiero caminar…',
      daysText: '¿Con qué frecuencia?',
      decreaseSteps: '-500 pasos',
      increaseSteps: '+500 pasos',
      decreaseDays: '-1 día',
      increaseDays: '+1 día',
      stepsPerDay: 'pasos/día',
      dayPerWeek: 'día/semana',
      daysPerWeek: 'días/semana',
    },
    stepGoalProgress: {
      thisWeek: 'Esta Semana',
      pastWeek: 'Semana Pasada',
      myGoal: 'Mi Meta',
      day: 'día',
      days: 'días',
      for: 'durante',
      inProgress: 'META EN CURSO',
      goalMet: 'META CUMPLIDA',
      goalNotMet: 'META NO CUMPLIDA',
      changeMyGoal: 'Cambiar mi objetivo',
      today: 'HOY',
      stepsToday: 'pasos hoy',
      avgStepsPerDay: 'promedio de pasos/día',
      moreStepsToGo: 'más pasos por recorrer',
      totalStepsThisWeek: 'pasos totales esta semana',
      mon: 'Lu',
      tue: 'Ma',
      wed: 'Mi',
      thu: 'Ju',
      fri: 'Vi',
      sat: 'Sá',
      sun: 'Do',
    },
  },
  zh: {
    common: {
      welcome: `歡迎來到\nLet’s Walk!`,
      next: '下一步',
      submit: '提交',
      today: '今天',
      yesterday: '昨天',
      noWalks: '還沒有行走',
      home: '主頁',
      back: '返回',
      myRecordedWalks: '我的步行記錄',
      about: `Let’s Walk信息`,
      programPartners: '計劃合作夥伴',
      topWalkers: '最佳步行者',
      whereToWalk: '去哪裡',
      emailUs: '電郵我們',
      contestRules: '比賽規則',
      privacyPolicy: '隱私條款',
      signOut: '登出',
      deleteUser: '刪除帳戶',
      steps: '步',
      miles: '英里',
      mins: '分鐘',
      morningWalk: '早上散步',
      afternoonWalk: '下午散步',
      eveningWalk: '傍晚散步',
      okay: '同意',
      pleaseWait: '請稍候...',
      serverErrorTitle: '意外錯誤',
      serverErrorMessage:
        `我們無法與Let’s Walk 服務器通信。請檢查您的互聯網連接並重試。`,
      date: 'M月D日',
      range: '{0}至{1}',
      rangeFrom: 'YYYY[年]M[月]D[日]',
      rangeTo: 'M月D日',
      dateSlash: 'YYYY[年]M[月]D[日]',
      save: '保存',
    },
    notifications: {
      repeatingRecordingReminder:
        '您已經走了一個小時。如果您已完成，別忘了暫停您的步行記錄！',
    },
    partners: {
      thanks: `特別鳴謝所有Let’s Walk贊助商！`,
      text: `Let’s Walk是由舊金山公共衛生局負責。由平等機會提供者USDA SNAP出資。社區合作夥伴包括加州公共衛生局，SF Civic Tech，舊金山巨人隊和舊金山康樂與公園部。`,
    },
    recorder: {
      finish: '保存',
      resume: '重新開始',
      stopAndSave: '停止並保存',
      stop: '停止',
      pause: '暫停',
      paused: '暫停',
      recording: '記錄',
      save: '保存{0}',
    },
    welcome: {
      select: '請選擇一種語言。',
      start: '開始',
    },
    signUp: {
      about:
        `Let’s Walk 是一項於{0}免費運行的社區步行計劃。該計劃向有資格參加CalFresh / Medical的舊金山居民開放。頂級步行者將有資格獲得舊金山巨人隊提供的獎品！在下面註冊即可開始！`,
      firstName: '名',
      lastName: '姓',
      email: '電子郵件',
      zipCode: '郵政編碼',
      age: '年齡',
      required: '* 需填寫字段',
      agree: '簽署即表示我同意{0}和{1}。',
      policy: '隱私條款',
      contestRules: '競賽規則',
      ageAlertTitle: '年龄限制',
      ageMinMessage: `您必須年滿18歲才能參與Let’s Walk。`,
      ageMaxMessage: '請輸入有效年齡。',
      emailAlertTitle: '需填電子郵件',
      emailAlertMessage: '請輸入有效的電子郵件地址。',
      zipRestrictionAlertTitle: '郵政編碼限制',
      zipRestrictionAlertMessage: `您必須是舊金山居民才能參加Let’s Walk。`,
    },
    info: {
      youreSignedUp: '您已註冊！',
      fromHereText: '從這裡開始，參與很容易！',
      walk: '步行！',
      walkText:
        '這個應用程式會計算您每天要走的總步數，步行時只需隨身攜帶手機即可。',
      record: '記錄！',
      recordText: '使用此功能跟蹤您的行走步數。增加行走距離和時間來挑戰自我！',
      win: '獲勝！',
      winText:
        '在該計劃結束後會通過電子郵件與前10名步行者聯繫，以領取獎品。獎品由舊金山巨人隊提供！',
    },
    permissions: {
      thingsToKnow: '事情需知。',
      takeALookText: '在開始之前請看以下信息。',
      settingsText: `Let’s Walk應用程序使用${Platform.select({
        ios: 'Apple Health',
        android: 'Google Fit',
      })}來跟蹤您的步數。在下一個屏幕中您將看到允許Let’s Walk使用的信息。`,
      prizeText: `您必須允許Let’s Walk應用程序使用${Platform.select({
        ios: 'Apple Health',
        android: 'Google Fit',
      })}信息才能贏取"Let’s Walk"獎品。所有信息將保密，僅用於"Let’s Walk"計劃。`,
      googleText: 'Google Fit需要一個Google帳戶，如果您沒有Google帳戶，{0}。',
      getOneHere: '請在此處了解如何獲取帳戶',
    },
    home: {
      stepsToday: '今天的步數',
      milesSuffix: '英里',
      milesToday: '今天的路程',
      overallStepTotal: '總步數',
      stepsThisMonth: '本月的總步數',
      topWalkers: '最佳步行者',
      whereToWalk: '需要一個散步的地方嗎？',
      myRecordedWalks: '我今天的步行記錄',
      allRecordedWalks: '所有的步行記錄',
      noWalksYet: '還沒有行走',
      noWalksYetText: '按下屏幕底部的“錄製”按鈕來開始新的步行。',
      recordAWalk: '記錄新步數',
      getReadyAlert1: '準備好開始挑戰！',
      getReadyAlert2:
        '從{0}起，您的步數總數將會重置並且您的步數將開始計入獲獎獎數中。',
      currentAlert: '目前的步行挑戰：{0} - {1}',
      congratsAlert:
        '恭喜您走得這麼好！如果您是一名頂級步行者，您將收到一封電子郵件並獲得獎品！挑戰現已結束，但您可以繼續使用該應用程序來追踪您的步數。',
      noContestAlert: '目前沒有步行挑戰，但請繼續行走！',
      myGoals: '我的目標',
    },
    whereToWalk: {
      options: '舊金山娛樂與公園部有很多活動可供選擇！',
      parksAndRecCenters: '公園和娛樂中心',
      hikingTrailsInSF: '舊金山的遠足徑',
      guidedWalks: '探索大自然',
      exerciseAndFitnessActivities: '運動與健身活動',
    },
    about: {
      what: `什麽是Let’s Walk？`,
      whatText:
        `Let’s Walk 是一項於{0}免費運行的社區步行計劃。該計劃向有資格參加CalFresh / Medical的舊金山居民開放。頂級步行者將有資格獲得舊金山巨人隊的獎品，其中包括比賽門票，簽名的裝備和特別獎品！`,
      dates: '關鍵日期？',
      datesText:
        '挑戰從{0}起，您的步行數將從零開始！{1}，您所有的步行數都將計入獎品中。計劃結束後，您可以使用該應用程序但不會獲得其他獎品。',
      prize: '我如何赢取獎品？',
      prizeText:
        '在該計劃結束後會通過電子郵件與前10名步行者聯繫，以領取獎品。獎品由舊金山巨人隊提供！',
    },
    latinOrHispanicOrigin: {
      select: '請從以下選項中選擇',
      question: '您是拉丁裔還是西班牙裔？',
      questionSub: '',
      yes: '是的',
      no: '不是',
      declineToAnswer: '拒絕回答',
      disclaimer: '所收集的信息將用於項目改進',
    },
    whatIsYourRace: {
      question: '您的種族是什麽？',
      questionSub: '如果您是多種族，請勾選所有適用的選項。',
      americanNative: '美洲印第安人或阿拉斯加原住民',
      asian: '亞裔',
      black: '非裔或非裔美國人',
      pacificIsl: '夏威夷原住民或其他太平洋島民',
      white: '白種人',
      other: '其他',
      otherSub: '請填寫：',
      cannotBeEmpty: '此處不能為空',
      declineToAnswer: '拒絕回答',
    },
    whatIsYourGenderIdentity: {
      question: '您的性别是？',
      questionSub: '',
      female: '女性',
      male: '男性',
      transFemale: '跨性别女性',
      transMale: '跨性别男性',
      nonBinary: '非二元性别',
      other: '其他',
      otherSub: '請填寫：',
      cannotBeEmpty: '此處不能為空',
      declineToAnswer: '拒絕回答',
    },
    whatIsYourSexualOrientation: {
      question: '你如何描述你的性取向或性身份？',
      questionSub: '',
      bisexual: '雙性戀',
      sameGenderLoving: '同性戀(男)/同性戀(女)/同性戀',
      unsure: '質疑/不確定',
      heterosexual: '異性戀',
      other: '其他',
      otherSub: '請填寫：',
      cannotBeEmpty: '此處不能為空',
      declineToAnswer: '拒絕回答',
    },
    deleteUser: {
      popupText: '您確定要刪除您所有儲存下來的資料嗎？',
      yesDelete: '是，刪除',
      noGoBack: '否，返回',
    },
    logout: {
      popupText: '您確定要退出嗎？',
      yesDelete: '是',
      noGoBack: '否，返回',
    },
    leaderBoard: {
      thisIsYou: '您在這裡！',
      walkerGeneral: '步行者',
      available: '僅限夏季：{0}',
      keepWalking: '繼續行走！',
    },
    setYourStepGoal: {
      header: '設定您的步數目標',
      instructions: '點擊按鈕來更改您的步數目標',
      stepText: '我想步行…',
      daysText: '多久一次？',
      decreaseSteps: '-500 步',
      increaseSteps: '+500 步',
      decreaseDays: '-1 天',
      increaseDays: '+1 天',
      stepsPerDayBefore: '每天',
      stepsPerDay: '步',
      // daysPerWeekBefore: '每週',
      dayPerWeek: '天/週',
      daysPerWeek: '天/週',
    },
    stepGoalProgress: {
      thisWeek: '本周',
      pastWeek: '上週',
      myGoal: '我的目標',
      day: '天',
      days: '天',
      for: '，持續',
      inProgress: '目標進展',
      goalMet: '達到目標',
      goalNotMet: '未達到目標',
      changeMyGoal: '改變我的目標',
      today: '今天',
      stepsToday: '今天的步數',
      avgStepsPerDay: '平均步數/天',
      moreStepsToGo: '還需增加更多步數',
      totalStepsThisWeek: '本週總步數',
      mon: '一',
      tue: '二',
      wed: '三',
      thu: '四',
      fri: '五',
      sat: '六',
      sun: '日',
    },
  },
});

export default Strings;
